version: "3.8"

services:
  frontend:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      ENV: dev
    networks:
      - local-rag-coop-frontend

  backend:
    build: ./src/backend/
    image: prosellen/rag-coop-backend
    ports:
      - "3001:3001"
    # args:
    #   - BUILD_ENV=${BUILD_ENV:-development}
    #   - CERT_FILE=${CERT_FILE:-/etc/ssl/certs/ca-certificates.crt}
    environment:
      BUILD_ENV: ${BUILD_ENV:-development}
      CERT_FILE: ${CERT_FILE:-/etc/ssl/certs/ca-certificates.crt}
    # command: ["python", "main.py"]
    develop:
      watch:
        - action: sync # Sync file changes without rebuilding
          path: . # Watch all files in the project directory
          target: /app # Sync changes into the container

  ollama:
    image: ollama/ollama
    depends_on:
      - chromadb
    networks:
      - local-rag-coop-frontend
      - local-rag-coop-backend

  chromadb:
    image: chromadb/chroma
    networks:
      - local-rag-coop-backend

networks:
  local-rag-coop-frontend:
  local-rag-coop-backend:
